sudo: true
language: haskell

# ghc:

cache:
  directories:
    - "$HOME/.cabal/store"
    - "$HOME/.stack"
    - "TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  - ghc: "7.10"
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack-7.10.yaml"
  - ghc: "7.8"
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack-7.8.yaml"
  - ghc: "8.4.4"
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack-8.4.4.yaml"
  - ghc: "8.6"
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack-7.8.yaml"
  - ghc: "8.8.4"
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack-8.8.4.yaml"

install:
  - |
    curl -sSL https://get.haskellstack.org/ | sh
    # build project with stack
    stack --version
    stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks


script:
  - |
    stack test --system-ghc

notifications:
  email: false
