sudo: true
language: haskell

# ghc:

cache:
  directories:
    - "$HOME/.cabal/store"
    - "$HOME/.stack"
    - "TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
    # Cabal
  - ghc: "8.4.4"
  - ghc: "8.6"
  - ghc: "8.8.4"
  - ghc: "8.10.2"

    # Stack
  - ghc: "7.10"
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack-7.10.yaml"
  - ghc: "7.8"
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack-7.8.yaml"

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      ghc --version
      cabal --version
      cabal update
      cabal build --enable-tests --enable-benchmarks
    else
      # install stack
      curl -sSL https://get.haskellstack.org/ | sh
      # build project with stack
      stack --version
      stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    fi


script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal test --enable-tests
    else
      stack test --system-ghc
    fi

notifications:
  email: false
